name: eda
channels:
  - conda-forge
  - defaults
dependencies:
  - pip
  - pip:
      - wandb
      - jupyterlab
      - seaborn
      - pandas
      - numpy
      - matplotlib
      - pandas-profiling
      - pyarrow
      - ipywidgets