name: basic_cleaning
channels:
  - conda-forge
  - defaults
dependencies:
  - pip=20.3.3
  - pip:
      - wandb
      - mlflow
      - scikit-learn
      - matplotlib
      - pillow==8.1.2
      - pandas
